@url = https://localhost:7054
@groupId = 6829910beb7115b6f328cec3
@labelId = 682992f9c762baeeb1d09172

### Get Expenses

GET {{url}}/api/groups/{{groupId}}/expenses/
Accept: application/json

### Add Expense

POST {{url}}/api/groups/{{groupId}}/expenses/
Content-Type: application/json

{
  "expenses": [
    {
      "name": "Test Expense",
      "amount": 100,
      "date": "2025-05-05T00:00:00Z",
      "labelId": "{{labelId}}"
    }
  ]
}

### Add Label

POST {{url}}/api/groups/{{groupId}}/labels
Content-Type: application/json

{
  "name": "Test Label",
  "icon": "🚀"
}

### Add group

POST {{url}}/api/groups
Content-Type: application/json

{
  "name": "Test Label",
  "UserIds": ["6828782ffa2e8ccd9bb40e61"]
}
