@url = https://localhost:7054
@groupId = 68287f9d842efd3b4f596000
@labelId = 682900e7b16dbc0a7f520262

### Get Expenses

GET {{url}}/api/groups/{{groupId}}/expenses/
Accept: application/json

### Add Expense

POST {{url}}/api/groups/{{groupId}}/expenses/
Content-Type: application/json

{
  "expenses": [
    {
      "name": "Test Expense",
      "amount": 100,
      "date": "2025-05-05T00:00:00Z",
      "labelId": "{{labelId}}"
    }
  ]
}

### Add Label

POST {{url}}/api/groups/{{groupId}}/labels
Content-Type: application/json

{
  "name": "Test Label",
  "icon": "🚀"
}
