import { B4hAuthProvider } from '../providers/authProvider';
import './global.css';
import { B4hHeader } from './header';

export const metadata = {
  title: 'Welcome to b4h-next',
  description: 'Generated by create-nx-workspace'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <B4hAuthProvider>
          <B4hHeader />
          {children}
        </B4hAuthProvider>
      </body>
    </html>
  );
}
