import { B4hHeader } from '../components/header/header';
import './global.scss';
import { Providers } from './providers';

import styles from './layout.module.scss';
import B4hHead from './head';

export const metadata = {
  title: 'Welcome to b4h-next',
  description: 'Generated by create-nx-workspace'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <B4hHead />
      <body>
        <Providers>
          <B4hHeader />
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
