import './global.css';
import B4hHead from './head';

export const metadata = {
  title: 'Welcome to b4h-next',
  description: 'Generated by create-nx-workspace'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <B4hHead />
      </head>
      <body>
        <main>{children}</main>
      </body>
    </html>
  );
}
