name: budget4home-backup/manual

on: workflow_dispatch

jobs:
  backup:
    name: backup 💾
    runs-on: ubuntu-latest
    steps:
      - name: backup 💾
        run: |
          curl -X POST -H "backup: ${{ secrets.BACKUP_KEY }}" https://budget4home.vercel.app/api/backup &&
          echo "DONE!"
        shell: bash
